=== chloecfq/resume/resume/data.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "About myself",
    "description": "Base info",
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "$schema": {
        "type": "string"
      },
      "name": {
          "description": "your name",
          "type": "string"
      },
      "career": {
          "description": "your career",
          "type": "string"
      },
      "school": {
          "type": "string"
      },
      "educationTime": {
          "type": "string"
      },
      "baseInfoTitle": {
          "type": "string"
      },
      "contactTitle": {
          "type": "string"
      },
      "baseInfo": {
        "type": "array",
        "items": {
          "$ref": "#/defs/info"
        }
      },
      "contactInfo": {
        "type": "array",
        "items": {
          "$ref": "#/defs/info"
        }
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "Works": {
        "type": "array",
        "items": {
            "$ref": "#/defs/work"
        }
    },
    "skill": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "title": {
              "type": "string"
            },
            "infoType": {
              "enum": [
                "evaluation",
                "skill",
                "field"
              ]
            },
            "fields": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "defs": {
        "info": {
            "required": ["key", "name", "content"],
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": ["tel", "mailto", "link", "none"]
                },
                "color": {
                    "type": "string"
                }
            }
        },
        "work": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "company": {
                "type": "string"
              },
              "project": {
                "type": "string"
              },
              "keyword": {
                "type": "string"
              },
              "description": {
                  "type": "string"
              }
            }
        }
    }
}

=== chloecfq/resume/public/resume/data.json
{
    "$schema": "./data.schema.json",
    "name": "陈凤群",
    "career": "iOS Developer",
    "school": "河南工业大学",
    "educationTime": "2012-2016",
    "baseInfoTitle": "基本信息",
    "contactTitle": "联系方式",
    "baseInfo": [
        {
            "name": "学历",
            "content": "本科",
            "key": "educatiion"
        },
        {
            "name": "专业",
            "content": "计算机科学与技术",
            "key": "professional"
        },
        {
            "name": "出生日期",
            "content": "1995-10-08",
            "key": "birthday"
        },
        {
            "name": "性别",
            "content": "女",
            "key": "gender"
        }
    ],
    "contactInfo": [
        {
            "name": "邮箱",
            "content": "orangescf@163.com",
            "key": "email",
            "type": "mailto",
            "color": "#7FB3D5"
        },
        {
            "name": "手机",
            "content": "18818697517",
            "key": "phone",
            "type": "tel"
        },
        {
            "name": "博客",
            "content": "https://orangeschen.cn",
            "key": "blog",
            "type": "link",
            "color": "#7FB3D5"
        }
    ],
    "tags": [
        "C",
        "Python",
        "Java",
        "php",
        "HTML",
        "Swift",
        "JavaScript",
        "Go"
    ],
    "skill": [
        {
            "title": "专业技能",
            "infoType": "field",
            "fields": [
                "熟练掌握 Objective-C，Swift，了解 C++/Python/TypeScript/Go 语言基础",
                "熟悉面向对象设计的基本原则、常用的设计模式、数据结构和算法",
                "熟悉大部分iOS开发与调试，理解iOS APP结构与运行机制，注重代码质量与执行效率",
                "熟悉 UI 设计、网络通信机制，了解 Socket 通信、TCP/IP 和 HTTPS",
                "熟悉 Git Flow工作流程，有较好的Git使用习惯，遵循团队开发规范",
                "对并发、Runloop、Runtime有一定的理解",
                "对开源框架有一定的了解，YYCache 的缓存方案",
                "对 APP 性能优化，业务解耦有有一定的理解",
                "了解 GraphQL 查询语言及 Apollo 使用",
                "了解 Sourcery 框架使用，并编写Stencil模版代码",
                "了解 TDD 开发模式，单元测试及移动端使用 Appium  e2e 测试",
                "了解 GCD、NSThread、NSOperationQueue 等多线程的使用",
                "了解 React、Flutter、小程序、Web 开发，有跨平台开发经验"
            ]
        },
        {
            "title": "技能清单",
            "infoType": "skill",
            "fields": [
                "前端框架：Angular/Remax/Next.js/React/Flutter",
                "数据库相关：MongoDB/kafka",
                "测试相关：Cypress/Appium/Airtest/Jest"
            ]
        },
        {
            "title": "自我评价",
            "infoType": "evaluation",
            "fields": [
                "对工作认真负责，有代码洁癖，严格遵守团队代码规范",
                "善于总结，具有较强的抗压能力",
                "性格开朗、乐观、具有良好的团队合作精神，适应能力强",
                "对新技术充满好奇，热衷于了解新技术"
            ]
        }
    ],
    "Works": [
        {
            "company": "深圳碳原子科技有限公司（2019.11-至今）",
            "project": "小电播",
            "keyword": "技术关键词：Redux、Appolo、GraphQL、React Native、CI/CD",
            "description": "主要负责直播和消息模块功能实现，APP 迭代开发，为了提高开发效率，方便团队快速开发，使用 Sourcery 编写 Stencil 代码，自动生成模块代码，优化重构 APP， 实现 APP 瘦身，编写持续集成工具配置，实现 Appium 自动化测试调研和使用。"
        },
        {
            "company": "",
            "project": "前端项目（SaaS平台、小电铺/小电播小程序、数据管理平台）",
            "keyword": "技术关键词：Angular、React、NG-ZORRO、Wepy、Remax、Cypress",
            "description": "维护公司现有的 SaaS 平台及小程序业务的迭代开发和遗留 bug 修复，负责编写前端自动化测试工具，实现 Web 自动化测试，参与公司创新项目-A/B测试平台中后台项目编写等。"
        },
        {
            "company": "深圳仟佰特科技有限公司 （2018. 7-2019. 9)",
            "project": "论购",
            "keyword": "",
            "description": "参与需求评审，负责客户端的开发、迭代和维护，用 Swift 对项目进行重构，提高性能，对接 bugly SDK，实时跟进线上反馈，解决线上问题，优化用户体验，优化项目，实现客户端提及瘦身。"
        },
        {
            "company": "深圳多新哆技术有限责任公司 （2016.7-2018.6）",
            "project": "多哚VR",
            "keyword": "技术关键词：VR、Unity 3D、ffmpeg、OpenGL ES",
            "description": "负责部分页面需求实现，优化项目图片缓存策略，对接 Unity 工程，配置工程环境，测试 Unity 场景数据，对接数据分析 SDK，将 SDK 分析的数据与 Unity 工程进行交互。"
        },
        {
            "company": "",
            "project": "Dloldo A1 SDK、Dlodlo VRPlayer桌面应用",
            "keyword": "技术关键词：OpenVR、DirectX11、ffmpeg、SDL、OpenCV",
            "description": "负责固件和客户端通讯SDK开发和维护，负责 Steam VRPlayer桌面应用需求开发。"
        }
    ]
}
